// angular/src/app/components/nav-bar/nav-bar.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.css'],
})
export class NavBarComponent {

}

<nav>
  <div class="wrapper">
    <img src="assets/img/logo.png" />
    <h1>cadastro de conta</h1>
  </div>
  <div class="right">
    <img src="assets/img/menu.png" />
  </div>
</nav>
<div class="separator"></div>

// react/src/components/NavBar/index.tsx
import React, { FC } from 'react'
import Logo from 'core/assets/images/logo.png'
import Menu from 'core/assets/images/menu.png'
import { Nav, Wrapper, Header, Right, Separator } from './styled'

const NavBar: FC = () => (
  <>
    <Nav>
      <Wrapper>
        <img src={Logo} />
        <Header>cadastro de conta</Header>
      </Wrapper>
      <Right>
        <img src={Menu} />
      </Right>
    </Nav>
    <Separator />
  </>
 )

export default NavBar
