// react/src/components/Form/Input/index.tsx
import React, { FC, useContext, useEffect, useState } from 'react'
import { StyledProperties } from 'core/constants/theme'
import { Group, Label } from '../styled'
import formContext from '../context'
import { Input as StyledInput } from './styled'

interface Props extends StyledProperties {
  name: string,
  label?: string,
  type?: string,
  value?: string,
  disabled?: boolean,
  autocomplete?: string,
  placeholder?: string,
}

const Input: FC<Props> = ({
  name,
  label,
  type,
  value: initialValue = '',
  disabled,
  autocomplete,
  placeholder,
  style,
}) => {
  const form = useContext(formContext)
  const [value, setValue] = useState(initialValue)

  useEffect(() => {
    form.setField(name, { value, hasError: false })
  }, [])

  useEffect(() => {
    form.setFieldValue(name, value)
  }, [value])

  return (
    <Group style={style}>
      <Label>{label}:</Label>
      <StyledInput
        name={name}
        type={type}
        value={value}
        onChange={event => setValue(event.target.value)}
        disabled={disabled}
        // @ts-ignore
        autocomplete={autocomplete}
        placeholder={placeholder}
      />
    </Group>
  )
}

export default Input

// angular/src/app/components/input/input.component.ts
import { Component, Input, ElementRef, AfterViewInit } from '@angular/core'
import { FormService, FormContext } from '../../services/form.service'
import { convertStyleToString } from '../../utils/style'

@Component({
  selector: 'app-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.css'],
})
export class InputComponent implements AfterViewInit {
  @Input() name: string
  @Input() label?: string
  @Input() type?: string
  @Input() value?: string
  @Input() disabled?: boolean
  @Input() autocomplete?: string
  @Input() placeholder?: string
  @Input() style?: Record<string, string>
  form: FormContext

  constructor(private formService: FormService, private element: ElementRef) {}

  setHostStyle() {
    const nativeElement = this.element.nativeElement as HTMLElement
    nativeElement.setAttribute('style', convertStyleToString(this.style))
  }

  initializeFormField() {
    this.form = this.formService.getFormInContext(this.element)
    this.form.setField(this.name, { value: this.value, hasError: false })
  }

  ngAfterViewInit() {
    this.setHostStyle()
    this.initializeFormField()
  }

  onChange() {
    this.form.setFieldValue(this.name, this.value)
  }
}

<div class="form-group">
  <label>{{label}}:</label>
  <input
    [name]="name"
    [disabled]="disabled"
    [type]="type || 'text'"
    [(ngModel)]="value"
    (input)="onChange()"
    [autocomplete]="autocomplete"
    [placeholder]="placeholder || ''"
  />
</div>
