// react/src/components/Form/Button/index.tsx
import React, { FC, useContext } from 'react'
import { StyledProperties } from 'core/constants/theme'
import formContext from '../context'
import { FormComponentEvent } from '../types'
import { Button as StyledButton } from './styled'

interface Props extends StyledProperties {
  onClick?: any,
  event?: FormComponentEvent,
  value: string,
  disabled?: boolean,
  type?: 'event' | 'submit' | 'reset' | 'button' | 'link',
  url?: string,
  style?: Record<string, string>,
}

const Button: FC<Props> = ({ type, onClick, event, value, disabled, url, style }) => {
  const form = useContext(formContext)

  const handleClick = () => {
    if (onClick) onClick()
    if (type === 'event' && event) form.handleFormEvent(event)
    if (type === 'link' && url)
      if (url.startsWith('/')) location.href = `${location.origin}${url}`
      else location.href = url
  }

  return (
    <StyledButton
      type={type === 'event' || type === 'link' ? 'button' : type}
      onClick={handleClick}
      style={style}
      disabled={disabled}
    >
      {value}
    </StyledButton>
  )
}

export default Button

// angular/src/app/components/button/button.component.ts
import { Component, Input, AfterViewInit, ElementRef } from '@angular/core'
import { FormComponentEvent } from '../form/form.component'
import { FormService, FormContext } from '../../services/form.service'

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.css'],
})
export class ButtonComponent implements AfterViewInit {
  @Input() onClick?: any
  @Input() event?: FormComponentEvent
  @Input() value: string
  @Input() disabled?: boolean
  @Input() type?: 'event' | 'submit' | 'reset' | 'button' | 'link'
  @Input() url?: string
  @Input() style?: Record<string, string>
  form: FormContext

  constructor(private formService: FormService, private element: ElementRef) {}

  handleClick() {
    if (this.onClick) this.onClick()
    if (this.type === 'event' && this.event && this.form) this.form.handleFormEvent(this.event)
    if (this.type === 'link' && this.url) {
      if (this.url.startsWith('/')) location.href = `${location.origin}${this.url}`
      else location.href = this.url
    }
  }

  ngAfterViewInit() {
    try {
      this.form = this.formService.getFormInContext(this.element)
    } catch {}
  }
}

<button
  [type]="type === 'event' || type === 'link' ? 'button' : type"
  (click)="handleClick()"
  [disabled]="disabled"
>
  {{value}}
</button>
